# worker
DB_USER = 'localhost'
DB_PASS = ''
DB_PORT = 27017
DB_BASE = 'forum'
WORKER_SERVERMQ = "localhost"
WORKER_VERBOSE = True
WORKER_FREQ = 4

# worker Home nav
WORKER_HOMENAV_START = 100
WORKER_HOMENAV_LEFT = True

# worker Home random
WORKER_HOMERANDOM_MIN = 0
WORKER_HOMERANDOM_MAX = 100